### ISSUE TITLE
F-Droid repo stuck on 3.4.9?

### ISSUE THREAD

**Issue by sudomain** [dkrivoruchko/ScreenStream#125] opened 2020-10-04 17:04 UTC
Maybe this is an FDroid thing, but I only see 3.4.9 on FDroid. I have the "include incompatible versions" setting enabled in the fdroid client, so I think I should be able to see newer versions if they were released. The [fdroiddata git repo seems to have more up to date versions](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/info.dvkr.screenstream.yml)

**Comment by dkrivoruchko** [comment] 2020-10-04 17:08
Duplicate of #107
The problem: =a bottom sheet dialog lib has a bug afollestad/material-dialogs#1825 that cause app crash

**Closed by dkrivoruchko** 2020-10-04 17:08 UTC
